export const CHAIN_ALIASES = {
  ETHEREUM_MAINNET: 1,
  SEPOLIA_TEST_NETWORK: 11155111,
  BSC_MAINNET: 56,
  BSC_TESTNET: 97,
};

export const AllowedNetwork = [
  CHAIN_ALIASES.ETHEREUM_MAINNET,
  CHAIN_ALIASES.SEPOLIA_TEST_NETWORK,
  CHAIN_ALIASES.BSC_MAINNET,
  CHAIN_ALIASES.BSC_TESTNET,
];
